### ISSUE TITLE
[3 suggestions] Add a "clear a counter/clear all counters" function; renaming; symbols 

### ISSUE THREAD

**Issue by Wikinaut** [arafatamim/tally-counter#7]
Three issues:

1.
The current "small dot" in the upper right corner currently removes a counter (you call it "delete"). I suggest to change the "dot" symbol to an "x" symbol and to rename the function (from "delete" to "remove counter"). 

2.
Moreover, for me it's more important to have functions:

- clear item counter (reset to "0")
- clear all items counter (reset all counters to "0")

3.
I also think I found a small bug: when you clear (delete) the counter field manually, counting is not possible, there must be a digit "0" in. So I suggest to check whether the string is empty or not-a-number and then to set it programmatically to "0" (zero),

Thanks for your nice program.

**Comment by arafatamim** [comment]
Fixed in 1.4

**Comment by Wikinaut** [comment]
Thank you!

**Comment by arafatamim** [comment]
You're welcome :-)

**Comment by Wikinaut** [comment]
Hello again… problem: I could not get the new code running, see https://github.com/arafatamim/tally-counter/issues/9
