### ISSUE TITLE
build / run error when using the instructions in README.md

### ISSUE THREAD

**Issue by Wikinaut** [arafatamim/tally-counter#9]
sudo npm run serve

> tabs@1.4.0 serve /home/benutzer/tally
> vite serve

qt.qpa.screen: QXcbConnection: Could not connect to display 
Could not connect to any X display.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tabs@1.4.0 serve: `vite serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tabs@1.4.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-20T00_32_21_256Z-debug.log

**Comment by arafatamim** [comment]
That's weird. Did you run `npm install` before running `npm run serve`?

**Comment by Wikinaut** [comment]
have a look. It wants to start X display, but the code is on a headless server. I have no idea what this "vite" means.

**Comment by arafatamim** [comment]
I am unable to reproduce the issue even without X display on my machine.
> `npm WARN Local package.json exists, but node_modules missing, did you mean to install?`

This error means that `npm` cannot find the required dependencies to build the app. You could try the instructions mentioned [here](https://stackoverflow.com/a/52122556/5125032).

Meanwhile, you can access the hosted version of the app [here](https://tally-counter-pwa.netlify.com).

**Comment by Wikinaut** [comment]
Yes, I skipped that ```npm install```, forgot it. Now it builds, but where can I set up the port?

**Comment by arafatamim** [comment]
I replaced `vue-cli` with `vite`, which uses a different port by default. You can change it in `vite.config.js` like this:
```
export default defineConfig({
  ...
  server: {
    port: "8080",
  },
});
```

**Comment by Wikinaut** [comment]
The browser is losing the connection after about 10…20 seconds and reloads then. Have you noticed that, too?
